"""Environment model: weather, ambient temperature and grid availability.

The environment is the main source of *uncertainty* in Pack 1. It is kept
deliberately simple and analytic so that a reviewer can read the code and see
exactly where every number comes from, and so that sensitivity variants can be
generated by perturbing a handful of parameters.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any


@dataclass
class WeatherProfile:
    """Diurnal temperature and solar irradiance.

    ASSUMED: sinusoidal temperature with a daily minimum at ``min_hour`` and a
    maximum at ``peak_hour``; solar irradiance a raised half-sine between
    sunrise and sunset, scaled by a per-day cloud factor.
    """

    profile_id: str = "SYNTHETIC-WX-001"
    description: str = "Northern European late-autumn, partly cloudy"
    temp_min_c: float = 3.0
    temp_max_c: float = 14.0
    peak_hour: float = 15.0
    min_hour: float = 4.0
    sunrise_hour: float = 7.0
    sunset_hour: float = 17.5
    clear_sky_peak_fraction: float = 0.72
    cloud_factor_by_day: list[float] = field(default_factory=lambda: [0.75, 0.45, 0.85])
    wind_speed_ms: float = 4.0
    data_labels: list[str] = field(default_factory=lambda: ["SYNTHETIC", "ASSUMED", "UNVALIDATED"])

    def temperature_c(self, hour: float) -> float:
        mean = 0.5 * (self.temp_max_c + self.temp_min_c)
        amplitude = 0.5 * (self.temp_max_c - self.temp_min_c)
        phase = 2.0 * math.pi * (hour - self.peak_hour) / 24.0
        return mean + amplitude * math.cos(phase)

    def cloud_factor(self, hour: float) -> float:
        if not self.cloud_factor_by_day:
            return 1.0
        day = int(hour // 24)
        return self.cloud_factor_by_day[min(day, len(self.cloud_factor_by_day) - 1)]

    def solar_fraction(self, hour: float) -> float:
        """Irradiance as a fraction of the array's peak rating (0..1)."""

        time_of_day = hour % 24.0
        if not (self.sunrise_hour <= time_of_day <= self.sunset_hour):
            return 0.0
        span = self.sunset_hour - self.sunrise_hour
        if span <= 0:
            return 0.0
        arc = math.sin(math.pi * (time_of_day - self.sunrise_hour) / span)
        return max(0.0, self.clear_sky_peak_fraction * arc * self.cloud_factor(hour))

    def to_dict(self) -> dict[str, Any]:
        return {
            "profile_id": self.profile_id,
            "description": self.description,
            "temp_min_c": self.temp_min_c,
            "temp_max_c": self.temp_max_c,
            "peak_hour": self.peak_hour,
            "min_hour": self.min_hour,
            "sunrise_hour": self.sunrise_hour,
            "sunset_hour": self.sunset_hour,
            "clear_sky_peak_fraction": self.clear_sky_peak_fraction,
            "cloud_factor_by_day": list(self.cloud_factor_by_day),
            "wind_speed_ms": self.wind_speed_ms,
            "data_labels": list(self.data_labels),
        }


@dataclass
class GridAvailability:
    """Availability of the civil / host-nation supply, hour by hour."""

    available_windows: list[list[float]] = field(default_factory=list)
    nominal_capacity_kw: float = 0.0
    note: str = ""

    def is_available_at(self, hour: float) -> bool:
        if not self.available_windows:
            return False
        return any(start <= hour < end for start, end in self.available_windows)

    def availability_fraction(self, duration_h: float) -> float:
        available = sum(
            max(0.0, min(end, duration_h) - max(0.0, start))
            for start, end in self.available_windows
        )
        return available / duration_h if duration_h else 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "available_windows": [list(w) for w in self.available_windows],
            "nominal_capacity_kw": self.nominal_capacity_kw,
            "note": self.note,
        }


@dataclass
class Environment:
    """Everything outside the node that the plan has to cope with."""

    environment_id: str = "SYNTHETIC-ENV-001"
    location_context: str = "Dispersed support node, temperate northern Europe (SYNTHETIC)"
    weather: WeatherProfile = field(default_factory=WeatherProfile)
    grid: GridAvailability = field(default_factory=GridAvailability)
    resupply_available: bool = False
    resupply_lead_time_h: float = 36.0
    threat_note: str = (
        "Not modelled in Pack 1. No adversary behaviour, no offensive action, "
        "no targeting. Disruptions are modelled as generic asset unavailability."
    )
    data_labels: list[str] = field(default_factory=lambda: ["SYNTHETIC", "ASSUMED", "UNVALIDATED"])

    def temperature_c(self, hour: float) -> float:
        return self.weather.temperature_c(hour)

    def solar_fraction(self, hour: float) -> float:
        return self.weather.solar_fraction(hour)

    def grid_available_at(self, hour: float) -> bool:
        return self.grid.is_available_at(hour)

    # --- uncertainty variants ----------------------------------------------

    def variant(
        self,
        *,
        name: str,
        temperature_offset_c: float = 0.0,
        cloud_scale: float = 1.0,
        grid_available: bool | None = None,
    ) -> "Environment":
        """Return a perturbed copy, used for sensitivity analysis (RQ-004)."""

        weather = replace(
            self.weather,
            profile_id=f"{self.weather.profile_id}/{name}",
            temp_min_c=self.weather.temp_min_c + temperature_offset_c,
            temp_max_c=self.weather.temp_max_c + temperature_offset_c,
            cloud_factor_by_day=[
                max(0.0, min(1.0, c * cloud_scale)) for c in self.weather.cloud_factor_by_day
            ],
        )
        grid = self.grid
        if grid_available is False:
            grid = GridAvailability(
                available_windows=[],
                nominal_capacity_kw=self.grid.nominal_capacity_kw,
                note="Sensitivity variant: grid assumed unavailable for the whole mission.",
            )
        return Environment(
            environment_id=f"{self.environment_id}/{name}",
            location_context=self.location_context,
            weather=weather,
            grid=grid,
            resupply_available=self.resupply_available,
            resupply_lead_time_h=self.resupply_lead_time_h,
            threat_note=self.threat_note,
            data_labels=list(self.data_labels),
        )

    def with_grid_windows(
        self, windows: list[list[float]], *, name: str, note: str = ""
    ) -> "Environment":
        """A copy whose host-nation supply follows different windows.

        Used to build the world that actually happened, as against the one the
        plan was made against.
        """

        return Environment(
            environment_id=f"{self.environment_id}/{name}",
            location_context=self.location_context,
            weather=self.weather,
            grid=GridAvailability(
                # A window that starts where it ends is not a window. Building
                # perturbed worlds out of a mission with several supply windows
                # can produce one; carrying it would put an empty interval in
                # front of anybody reading the mission's premise.
                available_windows=[
                    list(window) for window in windows if float(window[1]) > float(window[0])
                ],
                nominal_capacity_kw=self.grid.nominal_capacity_kw,
                note=note or self.grid.note,
            ),
            resupply_available=self.resupply_available,
            resupply_lead_time_h=self.resupply_lead_time_h,
            threat_note=self.threat_note,
            data_labels=list(self.data_labels),
        )

    # --- serialisation ------------------------------------------------------

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "Environment":
        return cls(
            environment_id=payload.get("environment_id", "SYNTHETIC-ENV-001"),
            location_context=payload.get("location_context", ""),
            weather=WeatherProfile(**payload["weather"]) if "weather" in payload else WeatherProfile(),
            grid=GridAvailability(**payload["grid"]) if "grid" in payload else GridAvailability(),
            resupply_available=payload.get("resupply_available", False),
            resupply_lead_time_h=payload.get("resupply_lead_time_h", 36.0),
            threat_note=payload.get("threat_note", ""),
            data_labels=payload.get("data_labels", ["SYNTHETIC", "ASSUMED", "UNVALIDATED"]),
        )

    @classmethod
    def from_file(cls, path: str | Path) -> "Environment":
        with open(path, "r", encoding="utf-8") as handle:
            return cls.from_dict(json.load(handle))

    def to_dict(self) -> dict[str, Any]:
        return {
            "environment_id": self.environment_id,
            "location_context": self.location_context,
            "weather": self.weather.to_dict(),
            "grid": self.grid.to_dict(),
            "resupply_available": self.resupply_available,
            "resupply_lead_time_h": self.resupply_lead_time_h,
            "threat_note": self.threat_note,
            "data_labels": list(self.data_labels),
        }
